### ISSUE TITLE
请教文中代码的具体实现问题

### ISSUE THREAD

**Issue by ithok** [lsh0520/RGCL#1]

**Comment by lsh0520** [comment]
请见论文中Eq（13）, P_R是rationale generator归一化输出，使得最终梯度可以反向传播至rationale generator

**Comment by ithok** [comment]
您好，我的理解是这样的，本身通过P_R采样节点生成R(g)这个地方是没有梯度的，但是因为对应的P_R参与了EQ13中的计算，所以P_R是在有梯度的（进而生成它的r(g)也会存在梯度）。

如果我的理解没有错误的话，那还有一个问题，就是是否RGCL的下游任务都只针对图分类任务进行（只粗略看了一下实验部分不是很确定），不然的话P_R这个操作如果针对节点级任务应该在我理解里不太能work，在对比loss里如果正负对也不好定义？

非常感谢您的回复！这对我很有帮助。

**Comment by ithok** [comment]
您好，请问可以回答这个问题吗？

**Comment by lsh0520** [comment]
我关闭了您另一个issue，我理解是同一个问题，就在这里一起回答了。
1. 目前RGCL是针对图分类任务的，如果要迁移到节点分类任务，应该需要重新思考修改。
2. Eq(13) 中x_r被用作计算对比损失，可以看到其中的GNN(R(g))项使得梯度可以传播到Backbone encoder，P_R由rationale generator产生，使得梯度可以传播到rationale generator。无监督学习setting也是这样。

**Comment by Lirain21** [comment]
Where can I get the datasets?
