### ISSUE TITLE
Question about enviroment

### ISSUE THREAD

**Issue by 66246764** [lsh0520/RGCL#5]
Hi，Thank you for the paper and the code！But may you share your environment about torch's version informations？The issues in "GCL" didn't make me fix this problem（old version problems），may you directly tell me the vesion informations？thanks a lot

**Comment by lsh0520** [comment]
![image](https://user-images.githubusercontent.com/28565053/197533601-cc537ad5-f61d-4370-b19e-d07d892e6154.png)
Pls see env.yml in this folder, which includes the version information of all packages.

**Comment by 66246764** [comment]
thanks!
